blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.blogHome, name="blogHome"),
    url(r'^add-blog/$', views.add_blog, name="add_blog"),
    url(r'^(?P<slug>[\w-]+)/$', views.blog_detail, name="detail"),
    url(r'^delete/(?P<slug>[\w-]+)/$', views.delete_blog, name="delete"),
    
]

tachyon/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home ),
    url(r'^blog/', include('blog.urls'))
]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
class Blogs(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    image = models.FileField(upload_to = 'media/', blank=True)


    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:100]+ '...'

blog/forms.py
from django.forms import ModelForm
from .models import Blogs

class Create(ModelForm):
    class Meta:
        model = Blogs
        fields = ['title', 'body', 'slug', 'image']

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Blogs
from .forms import Create

def add_blog(request):
    if request.method == "POST":
        addBlog = Create(request.POST, request.FILES)
        if addBlog.is_valid():
            addBlog.save()
            return redirect('blog:blogHome')
    else:
      addBlog = Create()
      return render(request, 'blog/create.html', {'addBlog':addBlog})


def blogHome(request):
    blogs = Blogs.objects.all().order_by('date')
    return render(request, 'blog/blogHome.html', {'blogs':blogs})

def blog_detail(request,slug):
    blog = Blogs.objects.get(slug=slug)
    return render(request, 'blog/blog_detail.html', {'blog':blog})


def delete_blog(request, slug):
    delBlog = Blogs.objects.filter(slug=slug).delete()
    return redirect('blog:blogHome')

tachyon/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

def home(request):
    return redirect('blog:blogHome')

blog/templates/blog/blogHome.html
{% extends "base_layout.html" %}
{% block contents%}
<h1>Tachyonics Blogs</h1>
<a class="btn btn-lg btn-success" href="{% url 'blog:add_blog' %}" role="button">Add Blog</a>

<div class="row">
  {% for blog in blogs%}
    <div class="col-md-6">
        <div class="card mb-2">
              <img src="{{blog.image.url}}" class="card-img-top">
              <div class="card-body">
                <h5 class="card-title"><a href="{% url 'blog:detail' slug=blog.slug %}">{{blog.title}}</a></h5>
                <p class="card-text">{{blog.snippet}}</p>
            </div>
            <div class="card-footer text-muted">
              {{blog.date}}
              <a class="btn btn-danger" href="{% url 'blog:delete' slug=blog.slug %}" role="button">Delete Blog</a>
            </div>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'base_layout.html'%}

{% block contents%}
<div class="container">
  <div class="row my-row">
    <div class="col-md-6">
      <img src="{{ blog.image.url }}" alt="" width=100%>
    </div>

    <div class="col-md-6">
      <h2>{{blog.title}}</h2>
      <div class="alert alert-primary" role="alert">
        {{blog.body}}
      </div>
      <div class="card-footer text-muted">
        {{blog.date}}
      </div>
    </div>

  </div>

</div>

{% endblock%}

blog/templates/blog/create.html
{% extends 'base_layout.html'%}

{% block contents%}
<div class="container">
  <h2>Add Blog</h2>
  <form action="/blog/add-blog/" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <label>Title: </label>
    {{addBlog.title}}
  </div>
  <div class="form-group">
    <label>Body: </label>
    {{addBlog.body}}
  </div>

  <div class="form-group">
    <label>Slug: </label>
    {{addBlog.slug}}
  </div>

  <div class="form-group">
      <label>media: </label>
    {{addBlog.image}}
  </div>

   <button type="submit" class="btn btn-primary">create blog</button>
    </form>
</div>

{% endblock%}

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>tachyonics blog</title>
    <link rel="shortcut icon" type="image/jpg" href="{%static 'django.jpg'%}"/>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css'%}">
  </head>
  <body>
    <div class="container">
      {% block contents%}

      {% endblock%}
    </div>
  </body>
  <script src="{% static 'bootstrap.min.js'%}"></script>
    <script src="{% static 'slugify.js'%}"></script>
</html>